---
title: "Day 07 Quiz on Hypothesis Tests"
author: "Carey Kopeikin"
date: "4/3/2022"
output: pdf_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, error=TRUE)
```


1. A start-up company is about to market a new computer printer. It decides to gamble by running commercials during the Super Bowl. The company hopes that name recognition will be worth the high cost of the ads. The goal of the company is that over 36% of the public recognize its brand name and associate it with computer equipment. The day after the game, a pollster contacts 420 randomly chosen adults and finds that 181 of them know that this company manufactures printers. Would you recommend that the company continue to advertise during Super Bowls? Explain.

a) Write appropriate hypotheses.


b) What is a type I error in this context? Explain the ramifications of that error.


c) What is a type II error in this context? Explain the ramifications of that error.


d) Which is worse for the company in this context?


e) Based on your answer to part d) is it better to use an alpha level of .05 or .01.


f) Perform the test and find the p-value using the alpha you selected in part e.


g) Make a graph


h) State your conclusion.





