---
title: "Day 07 Quiz on Hypothesis Tests Version 2"
author: "Carey Kopeikin"
date: "4/3/2022"
output: pdf_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, error=TRUE)
```


1. A 1996 report from the U.S. Consumer Product Safety Commission claimed that at least 90% of all American homes have at least one smoke detector. A city’s fire department has been running a public safety campaign about smoke detectors consisting of posters, billboards, and ads on radio and TV and in the newspaper. The city wonders if this concerted effort has raised the local level above the 90% national rate. Building inspectors visit 400 randomly selected homes and find that 376 have smoke detectors. Is this strong evidence that the local rate is higher than the national rate?

a) Write appropriate hypotheses.


b) What is a type I error in this context? Explain the ramifications of that error.


c) What is a type II error in this context? Explain the ramifications of that error.


d) Which is worse for the fire department in this context?


e) Based on your answer to part d) is it better to use an alpha level of .05 or .01.


f) Perform the test and find the p-value using the alpha you selected in part e.


g) Make a graph


h) State your conclusion.





2. A study in 1994 examined 491 dogs that had developed cancer and 945 dogs as a control group to determine whether there is an increased risk of cancer in dogs that are exposed to the herbicide 2,4-Dichlorophenoxyacetic acid (2,4-D). 

The file ```cancer_in_dogs.csv``` is a sample of some dogs who have been exposed to the herbicide (2,4-D) and whether they developed cancer or not. Note that of those dogs not exposed to the herbicide 33% tend to develop cancer. Does exposure increase the risk of cancer?



a) Write appropriate hypotheses.


b) What is a type I error in this context? Explain the ramifications of that error.


c) What is a type II error in this context? Explain the ramifications of that error.


d) Which is worse for the herbicide creator in this context?


e) Based on your answer to part d) is it better to use an alpha level of .05 or .01.


f) Perform the test and find the p-value using the alpha you selected in part e.


g) Make a graph


h) State your conclusion.


