---
title: "Day 06 Review 2 "
author: "Carey Kopeikin"
date: "3/21/2022"
output: pdf_document
---
 
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, error=TRUE)
```



1. A study in 1994 examined dogs to determine whether there is an increased risk of cancer in dogs that are exposed to the herbicide 2,4-Dichlorophenoxyacetic acid (2,4-D). The results of the dogs who were exposed are in ```../../data/cancer_in_dogs1.csv```. In general 32% of dogs who are not exposed to the herbicide develop cancer. 

a) Write appropriate hypotheses.

b) What is a type I error in this context? Explain the ramifications of that error.

c) What is a type II error in this context? Explain the ramifications of that error.

d) Which is worse in this context?

e) Based on your answer to part d) is it better to use an alpha level of .05 or .01.

f) Perform the test and find the p-value using the alpha you selected in part e.

g) Make a graph

h) State your conclusion.




2. Californians love there In-N-Out Burgers. It is so popular that your friend from California states that 70% of Californians would say In-N-Out makes the best burgers. You think it is less and Collect a survey of 500 respondents. The file ```../../data/burger.csv``` contains the results. We have information on their gender and their favorite burger joint. Set up an appropriate hypothesis test to see who wins the bet? 

a) Write appropriate hypotheses.

b) What is a type I error in this context? Explain the ramifications of that error.

c) What is a type II error in this context? Explain the ramifications of that error.

d) Which is worse in this context?

e) Based on your answer to part d) is it better to use an alpha level of .05 or .01.

f) Perform the test and find the p-value using the alpha you selected in part e.

g) Make a graph

h) State your conclusion.

